name: djones.co
description: Personal website and blog of Daniel Jones.
url: http://djones.co
permalink: /blog/:year/:month/:day/:title
exclude:
- README.md
- upload
- build
- trim
- assets
- sass
- config.rb
